# Generated by Django 5.2.11 on 2026-02-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
